language: node_js
node_js:
  - '7'
  - '6.9.1'
  - '4'
before_install:
  - 'npm install -g npm@3.10.8'
services:
  - mongodb
before_script:
  - sleep 15
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
